export const API_ENDPOINTS: Record<string, string> = {
  ADDRESS:"addresses",
  PRODUCTS: "products",
  SETTINGS: "settings",
  FAQ:"faqs",
  CUSTOMER: "me",
  COUPONS: "coupons",
  CATEGORY: "categories",
  PARENT_CATEGORIES: "fetch-parent-category",
  TYPE: "types",
  UPLOAD: "attachments",
  ORDER: "orders",
  ORDER_STATUS: "order_status",
  LOGIN: "token",
  SOCIAL_LOGIN: "social-login-token",
  REGISTER: "register",
  FORGET_PASSWORD: "forget-password",
  LOGOUT: "logout",
  CHANGE_PASSWORD: "change-password",
  RESET_PASSWORD: "reset-password",
  VERIFY_FORGET_PASSWORD: "verify-forget-password-token",
  VERIFY_CHECKOUT: "checkout/verify",
  CONTACT: "contact",
  ADDRESS: "address",
  SHOPS: "all-shop",
  STRIPE_CREATE:"stripe-create",
  SRIPE_CARD_DELETE:"stripe-card-delete",
  SHIPPINGS:"shippings",
  TICKET:"ticket",
  NOTICE:"notices",
  ARTICLE:"articles",
  REFUND:"refunds",
  BRAND:"brands",
  PLATFORM:"platforms",
  GAME:"games",
  PURCHASE_GAME:"purchase-games",
  REPAIR:"repairs"
  
};
