export const ROUTES = {
  HOME: "/",
  CHECKOUT: "/checkout",
  DASHBOARD: "/dashboard",
  PROFILE: "/profile",
  CHANGE_PASSWORD: "/change-password",
  ORDERS: "/orders",
  HELP: "/help",
  LOGOUT: "/logout",
  OFFERS: "/offers",
  ORDER_RECEIVED: "/order-received",
  PRODUCT: "/products",
  ORDER: "/order",
  PRIVACY: "/privacy",
  TERMS: "/terms",
  CONTACT: "/contact",
  SHOPS: "/shops",
  SUPPORTS:"/supports",
  REFUND:"/refunds",
  REPAIR:"/repair",
  SALE:"/games"
};
