export { AttributeIcon } from "@components/icons/sidebar/attribute";
export { AttributeValueIcon } from "@components/icons/sidebar/attribute-value";
export { CategoriesIcon } from "@components/icons/sidebar/categories";
export { CouponsIcon } from "@components/icons/sidebar/coupons";
export { OrdersIcon } from "@components/icons/sidebar/orders";
export { OrdersStatusIcon } from "@components/icons/sidebar/order-status";
export { ProductsIcon } from "@components/icons/sidebar/products";
export { DashboardIcon } from "@components/icons/sidebar/dashboard";
export { SettingsIcon } from "@components/icons/sidebar/settings";
export { ShopIcon } from "@components/icons/sidebar/shop";
export { MyShopIcon } from "@components/icons/sidebar/my-shop";
export { TagIcon } from "@components/icons/sidebar/tags";
export { TypesIcon } from "@components/icons/sidebar/types";
export { UsersIcon } from "@components/icons/sidebar/users";
export { ShippingsIcon } from "@components/icons/sidebar/shippings";
export { WithdrawIcon } from "@components/icons/sidebar/withdraw";
export { TaxesIcon } from "@components/icons/sidebar/taxes";
export {SupportIcon} from "@components/icons/sidebar/support";
export  {PromotionIcon} from "@components/icons/sidebar/promotion";
export {ArticleIcon} from "@components/icons/sidebar/article";
export {OutilMagic} from "@components/icons/sidebar/outil-magic";
export {DollarIcon} from "@components/icons/sidebar/dollar";
export {ClickCollect} from "@components/icons/sidebar/ClickCollect";
export {EmailIcon} from "@components/icons/sidebar/email";
export {RefundIcon} from "@components/icons/sidebar/refund";
export {PasswordIcon} from "@components/icons/sidebar/password";
export {LogoutIcon} from "@components/icons/sidebar/logout";
export {SubscriptionIcon} from "@components/icons/sidebar/subscription";
export {StartIcon} from "@components/icons/sidebar/start";
export {RepairIcon} from "@components/icons/sidebar/repair";
